version: '3'
services:
  server:
    container_name: node-express
    restart: always
    build: ./server
    command: node index.js
    ports:
      - '3000:3000'
    links:
      - mongo
  client:
    container_name: vue-frontend
    restart: always
    build: ./client
    command: npm run serve
    ports:
      - '8080:8080'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
