version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: ./app
    command: node index.js
    ports:
      - '80:3000'
    links:
      - mongo
  client:
    container_name: vuefrontend
    restart: always
    build: ./client
    command: quasar dev
    ports:
      - '8080:8080'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
